# Generated by Django 4.2.4 on 2023-08-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='Product_App/media/')),
                ('marginal_price', models.IntegerField()),
                ('orginal_price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_App.product_category')),
            ],
        ),
    ]
