# Generated by Django 4.2.4 on 2023-09-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='cat_image',
            field=models.ImageField(null=True, upload_to='Product_App/media/'),
        ),
    ]
