# Generated by Django 4.2.4 on 2023-09-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart_App', '0002_rename_user_id_cart_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
