# Generated by Django 4.2.4 on 2023-08-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_Profile_App', '0004_remove_user_info_id_alter_user_info_user_email_and_more'),
        ('Product_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_App.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Profile_App.user_info')),
            ],
        ),
    ]
