# Generated by Django 4.2.4 on 2023-09-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='phone',
        ),
    ]
