# Generated by Django 4.2.4 on 2023-08-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_Profile_App', '0002_delete_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=50)),
                ('user_pic', models.ImageField(upload_to='User_Profile_App/media/')),
                ('user_phone', models.CharField(max_length=50)),
                ('user_pin', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=100)),
                ('user_gender', models.CharField(max_length=50)),
            ],
        ),
    ]
