# Generated by Django 4.2.4 on 2023-08-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile_App', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
