# Generated by Django 4.2.4 on 2023-09-12 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User_Profile_App', '0004_remove_user_info_id_alter_user_info_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
