# Generated by Django 4.2.4 on 2023-09-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile_App', '0005_alter_user_info_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='user_email',
            new_name='email',
        ),
    ]
