# Generated by Django 4.2.4 on 2023-09-12 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User_Profile_App', '0006_rename_user_email_user_info_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user_info',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
