# Generated by Django 4.2.4 on 2023-09-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile_App', '0007_remove_user_info_user_name_user_info_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='username',
        ),
    ]
