# Generated by Django 4.2.4 on 2023-09-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile_App', '0008_remove_user_info_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='user_address',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='user_gender',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='user_password',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='user_phone',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='user_pic',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='user_pin',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
