# Generated by Django 4.2.4 on 2023-09-12 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User_Profile_App', '0009_remove_user_info_email_remove_user_info_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='user_id',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='user_info',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='alt_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
