# Generated by Django 4.2.3 on 2023-09-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile_App', '0010_rename_user_id_user_info_phone_user_info_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_img',
            field=models.ImageField(null=True, upload_to='User_Profile_App/media/'),
        ),
    ]
